<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

//Generated By PlantUML Command
class Actividad extends Model
{
    protected $fillable = [
        'nombre',
        'horario',
        'dia',
    ];

    public function recintoactividads()
    {
        return $this->hasMany('App\Models\RecintoActividad');
    }

    public function recintoactividad()
    {
        return $this->belongsTo('App\Models\RecintoActividad');
    }
}
