<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

//Generated By PlantUML Command
class Cuidador extends Model
{
    protected $fillable = [
        'nombre',
        'apellido',
        'edad',
        'especialidad',
    ];

    public function animalcuidadors()
    {
        return $this->hasMany('App\Models\AnimalCuidador');
    }

    public function animalcuidador()
    {
        return $this->belongsTo('App\Models\AnimalCuidador');
    }

    public function especiecuidadors()
    {
        return $this->hasMany('App\Models\EspecieCuidador');
    }

    public function especiecuidador()
    {
        return $this->belongsTo('App\Models\EspecieCuidador');
    }
}
