<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

//Generated By PlantUML Command
class EspecieCuidador extends Model
{
    protected $fillable = [
        'especie_id',
        'cuidador_id',
    ];

    public function cuidador()
    {
        return $this->belongsTo('App\Models\Cuidador');
    }

    public function especies()
    {
        return $this->belongsToMany('App\Models\Especie');
    }
}
