<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

//Generated By PlantUML Command
class Recinto extends Model
{
    protected $fillable = [
        'nombre',
        'animal_id',
    ];

    public function recintoactividads()
    {
        return $this->belongsToMany('App\Models\RecintoActividad');
    }

    public function recintoactividad()
    {
        return $this->belongsTo('App\Models\RecintoActividad');
    }
}
