<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

//Generated By PlantUML Command
class RecintoActividad extends Model
{
    protected $fillable = [
        'recinto_id',
        'actividad_id',
    ];

    public function actividad()
    {
        return $this->belongsTo('App\Models\Actividad');
    }

    public function recintos()
    {
        return $this->belongsToMany('App\Models\Recinto');
    }
}
